"""Global constants."""

DEFAULT_MAX_STEPS_MAIN = 10
DEFAULT_MAX_STEPS_GUI = 30
DEFAULT_MAX_STEPS_TEXT = 20
DEFAULT_BASH_TIMEOUT = 30
DEFAULT_SCREENSHOT_MAX_WIDTH = 1280
DEFAULT_SCREENSHOT_MAX_HEIGHT = 800
DEFAULT_A11Y_MAX_DEPTH = 5
DEFAULT_LLM_MAX_TOKENS = 4096
DEFAULT_LLM_TEMPERATURE = 0.0
DEFAULT_SERVER_HOST = "127.0.0.1"
DEFAULT_SERVER_PORT = 8000
